export const spanishWords = [
  { word: 'Amor', definition: 'Love', audioSrc: '/audio/es/amor.mp3' },
  { word: 'Felicidad', definition: 'Happiness', audioSrc: '/audio/es/felicidad.mp3' },
  { word: 'Esperanza', definition: 'Hope', audioSrc: '/audio/es/esperanza.mp3' },
  { word: 'Amistad', definition: 'Friendship', audioSrc: '/audio/es/amistad.mp3' },
  { word: 'Paz', definition: 'Peace', audioSrc: '/audio/es/paz.mp3' },
  { word: 'Libertad', definition: 'Freedom', audioSrc: '/audio/es/libertad.mp3' },
  { word: 'Fuerza', definition: 'Strength', audioSrc: '/audio/es/fuerza.mp3' },
  { word: 'Sabiduría', definition: 'Wisdom', audioSrc: '/audio/es/sabiduria.mp3' },
  { word: 'Coraje', definition: 'Courage', audioSrc: '/audio/es/coraje.mp3' },
  { word: 'Compasión', definition: 'Compassion', audioSrc: '/audio/es/compasion.mp3' },
  { word: 'Gratitud', definition: 'Gratitude', audioSrc: '/audio/es/gratitud.mp3' },
  { word: 'Paciencia', definition: 'Patience', audioSrc: '/audio/es/paciencia.mp3' },
  { word: 'Respeto', definition: 'Respect', audioSrc: '/audio/es/respeto.mp3' },
  { word: 'Honestidad', definition: 'Honesty', audioSrc: '/audio/es/honestidad.mp3' },
  { word: 'Lealtad', definition: 'Loyalty', audioSrc: '/audio/es/lealtad.mp3' },
  { word: 'Generosidad', definition: 'Generosity', audioSrc: '/audio/es/generosidad.mp3' },
  { word: 'Tolerancia', definition: 'Tolerance', audioSrc: '/audio/es/tolerancia.mp3' },
  { word: 'Perseverancia', definition: 'Perseverance', audioSrc: '/audio/es/perseverancia.mp3' },
  { word: 'Integridad', definition: 'Integrity', audioSrc: '/audio/es/integridad.mp3' },
  { word: 'Empatía', definition: 'Empathy', audioSrc: '/audio/es/empatia.mp3' },
  { word: 'Dignidad', definition: 'Dignity', audioSrc: '/audio/es/dignidad.mp3' },
  { word: 'Solidaridad', definition: 'Solidarity', audioSrc: '/audio/es/solidaridad.mp3' },
  { word: 'Confianza', definition: 'Trust', audioSrc: '/audio/es/confianza.mp3' }
];

export const japaneseWords = [
  { word: '愛', definition: 'Love', audioSrc: '/audio/jp/愛.mp3' },
  { word: '幸せ', definition: 'Happiness', audioSrc: '/audio/jp/幸せ.mp3' },
  { word: '希望', definition: 'Hope', audioSrc: '/audio/jp/希望.mp3' },
  { word: '友情', definition: 'Friendship', audioSrc: '/audio/jp/友情.mp3' },
  { word: '平和', definition: 'Peace', audioSrc: '/audio/jp/平和.mp3' },
  { word: '自由', definition: 'Freedom', audioSrc: '/audio/jp/自由.mp3' },
  { word: '強さ', definition: 'Strength', audioSrc: '/audio/jp/強さ.mp3' },
  { word: '知恵', definition: 'Wisdom', audioSrc: '/audio/jp/知恵.mp3' },
  { word: '勇気', definition: 'Courage', audioSrc: '/audio/jp/勇気.mp3' },
  { word: '思いやり', definition: 'Compassion', audioSrc: '/audio/jp/思いやり.mp3' },
  { word: '感謝', definition: 'Gratitude', audioSrc: '/audio/jp/感謝.mp3' },
  { word: '忍耐', definition: 'Patience', audioSrc: '/audio/jp/忍耐.mp3' },
  { word: '尊敬', definition: 'Respect', audioSrc: '/audio/jp/尊敬.mp3' },
  { word: '誠実', definition: 'Honesty', audioSrc: '/audio/jp/誠実.mp3' },
  { word: '忠誠', definition: 'Loyalty', audioSrc: '/audio/jp/忠誠.mp3' },
  { word: '寛大', definition: 'Generosity', audioSrc: '/audio/jp/寛大.mp3' },
  { word: '寛容', definition: 'Tolerance', audioSrc: '/audio/jp/寛容.mp3' },
  { word: '忍耐力', definition: 'Perseverance', audioSrc: '/audio/jp/忍耐力.mp3' },
  { word: '誠実さ', definition: 'Integrity', audioSrc: '/audio/jp/誠実さ.mp3' },
  { word: '共感', definition: 'Empathy', audioSrc: '/audio/jp/共感.mp3' },
  { word: '尊厳', definition: 'Dignity', audioSrc: '/audio/jp/尊厳.mp3' },
  { word: '連帯', definition: 'Solidarity', audioSrc: '/audio/jp/連帯.mp3' },
  { word: '信頼', definition: 'Trust', audioSrc: '/audio/jp/信頼.mp3' }
];
